out_file = "/home/cpe454/Desktop/OS/src/c/isr.h"
isr_count = 256

content = """/**
FILE GENERATED BY /home/cpe454/Desktop/OS/src/py/isr_header_generator.py
ANY CHANGES TO THIS FILE WILL BE OVERWRITTEN BY THE SCRIPT
*/

#ifndef ISR_H
#define ISR_H

"""

for i in range(isr_count):
	content += f"extern void isr{i}(void);\n"

content += """
typedef void (*isr_func)(void);

// Each index i has function pointer to isr$i 
isr_func isr_func_table[] = {
"""

for i in range(isr_count):
	content += f"isr{i},"

content += """};

#endif"""

with open(out_file, "w") as f:
	f.write(content)